export type DestinationInfo = {
  name: string;
  country: string;
  highlights: string[];
};

export const TOP_DESTINATIONS: DestinationInfo[] = [
  { name: "Toronto", country: "Canada", highlights: ["CN Tower", "Distillery District", "Toronto Islands"] },
  { name: "Vancouver", country: "Canada", highlights: ["Stanley Park", "Granville Island", "Capilano Bridge"] },
  { name: "Montreal", country: "Canada", highlights: ["Old Montreal", "Mount Royal", "Jean-Talon Market"] },
  { name: "Quebec City", country: "Canada", highlights: ["Old Quebec", "Chateau Frontenac", "Plains of Abraham"] },
  { name: "Calgary", country: "Canada", highlights: ["Calgary Tower", "Stephen Avenue", "Heritage Park"] },
  { name: "Banff", country: "Canada", highlights: ["Lake Louise", "Banff Gondola", "Hot Springs"] },
  { name: "New York City", country: "USA", highlights: ["Central Park", "Times Square", "Statue of Liberty"] },
  { name: "Los Angeles", country: "USA", highlights: ["Hollywood", "Santa Monica Pier", "Griffith Observatory"] },
  { name: "San Francisco", country: "USA", highlights: ["Golden Gate Bridge", "Alcatraz", "Fisherman's Wharf"] },
  { name: "Chicago", country: "USA", highlights: ["Millennium Park", "Navy Pier", "Art Institute"] },
  { name: "Seattle", country: "USA", highlights: ["Pike Place Market", "Space Needle", "Museum of Pop Culture"] },
  { name: "Miami", country: "USA", highlights: ["South Beach", "Wynwood Walls", "Little Havana"] },
  { name: "Las Vegas", country: "USA", highlights: ["The Strip", "Bellagio Fountains", "Red Rock Canyon"] },
  { name: "Boston", country: "USA", highlights: ["Freedom Trail", "Boston Common", "Harvard Square"] },
  { name: "Washington DC", country: "USA", highlights: ["National Mall", "Smithsonian Museums", "Georgetown"] },
  { name: "New Orleans", country: "USA", highlights: ["French Quarter", "Bourbon Street", "Garden District"] },
  { name: "Austin", country: "USA", highlights: ["Live Music", "Lady Bird Lake", "South Congress"] },
  { name: "Denver", country: "USA", highlights: ["Red Rocks", "Union Station", "Denver Art Museum"] },
  { name: "San Diego", country: "USA", highlights: ["Balboa Park", "Gaslamp Quarter", "La Jolla Cove"] },
  { name: "Honolulu", country: "USA", highlights: ["Waikiki Beach", "Diamond Head", "Pearl Harbor"] },
  { name: "Orlando", country: "USA", highlights: ["Theme Parks", "Disney Springs", "Lake Eola"] },
  { name: "London", country: "UK", highlights: ["Tower of London", "British Museum", "Borough Market"] },
  { name: "Paris", country: "France", highlights: ["Eiffel Tower", "Louvre", "Montmartre"] },
  { name: "Rome", country: "Italy", highlights: ["Colosseum", "Trevi Fountain", "Vatican City"] },
  { name: "Milan", country: "Italy", highlights: ["Duomo", "Galleria Vittorio Emanuele II", "Brera District"] },
  { name: "Venice", country: "Italy", highlights: ["Grand Canal", "St Mark's Basilica", "Rialto Bridge"] },
  { name: "Florence", country: "Italy", highlights: ["Duomo", "Uffizi Gallery", "Ponte Vecchio"] },
  { name: "Barcelona", country: "Spain", highlights: ["Sagrada Familia", "Park Guell", "Gothic Quarter"] },
  { name: "Madrid", country: "Spain", highlights: ["Prado Museum", "Retiro Park", "Plaza Mayor"] },
  { name: "Lisbon", country: "Portugal", highlights: ["Belem", "Alfama", "Tram 28"] },
  { name: "Porto", country: "Portugal", highlights: ["Ribeira", "Livraria Lello", "Port Wine"] },
  { name: "Amsterdam", country: "Netherlands", highlights: ["Canal Ring", "Rijksmuseum", "Jordaan"] },
  { name: "Brussels", country: "Belgium", highlights: ["Grand Place", "Atomium", "Comic Strip Route"] },
  { name: "Berlin", country: "Germany", highlights: ["Brandenburg Gate", "Museum Island", "East Side Gallery"] },
  { name: "Munich", country: "Germany", highlights: ["Marienplatz", "English Garden", "Nymphenburg Palace"] },
  { name: "Prague", country: "Czech Republic", highlights: ["Charles Bridge", "Old Town Square", "Prague Castle"] },
  { name: "Vienna", country: "Austria", highlights: ["Schonbrunn Palace", "St Stephen's Cathedral", "MuseumsQuartier"] },
  { name: "Budapest", country: "Hungary", highlights: ["Parliament", "Buda Castle", "Thermal Baths"] },
  { name: "Zurich", country: "Switzerland", highlights: ["Old Town", "Lake Zurich", "Uetliberg"] },
  { name: "Geneva", country: "Switzerland", highlights: ["Jet d'Eau", "Old Town", "Lake Geneva"] },
  { name: "Reykjavik", country: "Iceland", highlights: ["Hallgrimskirkja", "Blue Lagoon", "Golden Circle"] },
  { name: "Dublin", country: "Ireland", highlights: ["Trinity College", "Guinness Storehouse", "Temple Bar"] },
  { name: "Edinburgh", country: "UK", highlights: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat"] },
  { name: "Glasgow", country: "UK", highlights: ["Kelvingrove", "Merchant City", "Riverside Museum"] },
  { name: "Oslo", country: "Norway", highlights: ["Opera House", "Vigeland Park", "Aker Brygge"] },
  { name: "Stockholm", country: "Sweden", highlights: ["Gamla Stan", "Vasa Museum", "Djurgarden"] },
  { name: "Copenhagen", country: "Denmark", highlights: ["Nyhavn", "Tivoli Gardens", "Rosenborg Castle"] },
  { name: "Helsinki", country: "Finland", highlights: ["Suomenlinna", "Market Square", "Design District"] },
  { name: "Athens", country: "Greece", highlights: ["Acropolis", "Plaka", "Ancient Agora"] },
  { name: "Santorini", country: "Greece", highlights: ["Oia", "Caldera Views", "Red Beach"] },
  { name: "Istanbul", country: "Turkey", highlights: ["Hagia Sophia", "Grand Bazaar", "Bosphorus"] },
  { name: "Dubrovnik", country: "Croatia", highlights: ["Old Town Walls", "Stradun", "Lokrum Island"] },
  { name: "Split", country: "Croatia", highlights: ["Diocletian's Palace", "Riva Promenade", "Marjan Hill"] },
  { name: "Krakow", country: "Poland", highlights: ["Main Square", "Wawel Castle", "Kazimierz"] },
  { name: "Warsaw", country: "Poland", highlights: ["Old Town", "Lazienki Park", "POLIN Museum"] },
  { name: "Marrakesh", country: "Morocco", highlights: ["Jemaa el-Fnaa", "Majorelle Garden", "Medina"] },
  { name: "Cairo", country: "Egypt", highlights: ["Pyramids of Giza", "Egyptian Museum", "Khan el-Khalili"] },
  { name: "Cape Town", country: "South Africa", highlights: ["Table Mountain", "V&A Waterfront", "Cape Point"] },
  { name: "Nairobi", country: "Kenya", highlights: ["Nairobi National Park", "Giraffe Centre", "Karen Blixen Museum"] },
  { name: "Zanzibar City", country: "Tanzania", highlights: ["Stone Town", "Forodhani Gardens", "Prison Island"] },
  { name: "Dubai", country: "UAE", highlights: ["Burj Khalifa", "Dubai Mall", "Desert Safari"] },
  { name: "Abu Dhabi", country: "UAE", highlights: ["Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Yas Island"] },
  { name: "Doha", country: "Qatar", highlights: ["Souq Waqif", "Museum of Islamic Art", "Corniche"] },
  { name: "Tel Aviv", country: "Israel", highlights: ["Jaffa", "Carmel Market", "Beach Promenade"] },
  { name: "Amman", country: "Jordan", highlights: ["Citadel", "Roman Theater", "Rainbow Street"] },
  { name: "Petra", country: "Jordan", highlights: ["Treasury", "Siq", "Monastery"] },
  { name: "Bangkok", country: "Thailand", highlights: ["Grand Palace", "Chatuchak Market", "Chao Phraya River"] },
  { name: "Chiang Mai", country: "Thailand", highlights: ["Old City Temples", "Night Bazaar", "Doi Suthep"] },
  { name: "Phuket", country: "Thailand", highlights: ["Patong Beach", "Phi Phi Islands", "Big Buddha"] },
  { name: "Singapore", country: "Singapore", highlights: ["Marina Bay Sands", "Gardens by the Bay", "Hawker Centers"] },
  { name: "Kuala Lumpur", country: "Malaysia", highlights: ["Petronas Towers", "Batu Caves", "Bukit Bintang"] },
  { name: "Hanoi", country: "Vietnam", highlights: ["Old Quarter", "Hoan Kiem Lake", "Temple of Literature"] },
  { name: "Ho Chi Minh City", country: "Vietnam", highlights: ["Ben Thanh Market", "War Remnants Museum", "Cu Chi Tunnels"] },
  { name: "Bali", country: "Indonesia", highlights: ["Ubud", "Tanah Lot", "Beach Clubs"] },
  { name: "Jakarta", country: "Indonesia", highlights: ["Old Town", "National Monument", "Grand Indonesia Mall"] },
  { name: "Manila", country: "Philippines", highlights: ["Intramuros", "Rizal Park", "Binondo"] },
  { name: "Cebu", country: "Philippines", highlights: ["Magellan's Cross", "Kawasan Falls", "Temple of Leah"] },
  { name: "Seoul", country: "South Korea", highlights: ["Gyeongbokgung", "Myeongdong", "Hongdae"] },
  { name: "Busan", country: "South Korea", highlights: ["Haeundae Beach", "Gamcheon Village", "Jagalchi Market"] },
  { name: "Tokyo", country: "Japan", highlights: ["Shibuya Crossing", "Asakusa", "Tokyo Skytree"] },
  { name: "Kyoto", country: "Japan", highlights: ["Fushimi Inari", "Arashiyama", "Gion"] },
  { name: "Osaka", country: "Japan", highlights: ["Dotonbori", "Osaka Castle", "Kuromon Market"] },
  { name: "Hiroshima", country: "Japan", highlights: ["Peace Memorial Park", "Miyajima", "Shukkeien Garden"] },
  { name: "Sydney", country: "Australia", highlights: ["Opera House", "Bondi Beach", "Harbour Bridge"] },
  { name: "Melbourne", country: "Australia", highlights: ["Laneways", "Queen Victoria Market", "Great Ocean Road"] },
  { name: "Brisbane", country: "Australia", highlights: ["South Bank", "Lone Pine Koala Sanctuary", "Story Bridge"] },
  { name: "Auckland", country: "New Zealand", highlights: ["Sky Tower", "Waiheke Island", "Viaduct Harbour"] },
  { name: "Queenstown", country: "New Zealand", highlights: ["Lake Wakatipu", "Shotover Jet", "Gondola"] },
  { name: "Rio de Janeiro", country: "Brazil", highlights: ["Christ the Redeemer", "Copacabana", "Sugarloaf Mountain"] },
  { name: "Sao Paulo", country: "Brazil", highlights: ["Avenida Paulista", "Ibirapuera Park", "Municipal Market"] },
  { name: "Buenos Aires", country: "Argentina", highlights: ["La Boca", "Recoleta", "San Telmo"] },
  { name: "Lima", country: "Peru", highlights: ["Miraflores", "Historic Center", "Barranco"] },
  { name: "Cusco", country: "Peru", highlights: ["Plaza de Armas", "Sacsayhuaman", "Sacred Valley"] },
  { name: "Mexico City", country: "Mexico", highlights: ["Zocalo", "Chapultepec Park", "Coyoacan"] },
  { name: "Cancun", country: "Mexico", highlights: ["Hotel Zone", "Isla Mujeres", "Chichen Itza"] },
  { name: "Havana", country: "Cuba", highlights: ["Old Havana", "Malecon", "Classic Cars"] },
  { name: "San Juan", country: "Puerto Rico", highlights: ["Old San Juan", "El Morro", "Condado Beach"] },
  { name: "Bogota", country: "Colombia", highlights: ["La Candelaria", "Monserrate", "Gold Museum"] },
  { name: "Cartagena", country: "Colombia", highlights: ["Walled City", "Castillo San Felipe", "Getsemani"] },
];
